#!/usr/bin/env bash

# Bash script to backup home directory

source ../lib/logging.sh

# Global constants
readonly BACKUP_DIR="/run/media/${USER}/T7/Backup/fedora/"

##########################
# Print usage for help
# Globals:
#   None
# Arguments:
#   None
# Outputs:
#   Writes usage to stdout
##########################
function print_help() {
    echo "Usage: $(basename -- "$0") [-h] [--new] [--postcheck]"
    echo "Backup home directory using restic"
    echo
    echo "-h, --help    prints this message"
    echo "--new         prints instructions on initializing a new restic repo"
    echo "--postcheck   runs integrrity check after backup"
}

#############################
# Preprocess checks before
# running main function
# Globals:
#   None
# Arguments:
#   None
# Outputs:
#   Writes preprocess results
#############################
function preprocess() {
  logging::debug "Checking if restic is installed"
  if ! command -v -- restic &> /dev/null; then
    logging::error "restic not found. Please install"
    exit 1
  fi

  logging::debug "Checking if backup dir exists"
  if [[ ! -d ${BACKUP_DIR} ]]; then
    logging::error "Backup directory doesn't exist: ${BACKUP_DIR}"
    exit 1
  fi
}

function main() {
  logging::set_level LOG_DEBUG
  preprocess

  if [[ ${isNew} == true ]]; then
    logging::info "Run the following command: restic init --repo /path/to/repo"
    logging::info "More info can be found in: https://restic.readthedocs.io/en/stable/030_preparing_a_new_repo.html"
    logging::info "Once repository is initialized, rerun this script without the --new flag"
    exit 0
  fi

  logging::info "Starting to backup"
  logging::debug "Running: restic -r ${BACKUP_DIR} --verbose backup ${HOME}"
  restic -r "${BACKUP_DIR}" --verbose backup ${HOME}

  logging::info "Finished backing up to: ${BACKUP_DIR}"

  if [[ ${doPostCheck} == true ]]; then
    logging::info "Performing post check"
    restic -r ${BACKUP_DIR} check --read-data
  fi
}

# Parse args
while [[ $# -gt 0 ]]; do
  case $1 in
    -h|--help)
      print_help
      exit
      ;;
    --new)
      isNew=true
      shift
      ;;
    --postcheck)
      doPostCheck=true
      shift
      ;;
    *)
      # Ignore positional args
      shift
      ;;
  esac
done

main
